### ISSUE TITLE
It is not clear how to use it into a Genie app

### ISSUE THREAD

**Issue by dmolina** [GenieFramework/GenieAutoreload.jl#8]
Thank you for the GenieFramework!
I am trying to use it to translate a Python website to Julia and I have tried this plugin but I could not use it after several tries.

The main problem is that it is not clear in the README how to use it inside an existing Genie website:

- The code in the README, where it should be included, and loaded?
- I guess the  assets() should be included into the layout, I tried  `<% GenieAutoReload.assets() %>`, but it said that it did not know GenieAutoReload, I include several using, but it didn't work.

Thanks in advance for your help.

**Comment by essenciary** [comment]
@dmolina Thanks - I will add some demo apps to the docs. 

The way I currently use it is: 

1/ I initialize it in `plugins/autoreload.jl` 

```julia
using GenieAutoReload
Genie.config.websockets_server = true
GenieAutoReload.autoreload(pwd())
```
2/ I add it to the layout file (eg `app.jl.html`)

```julia
<%
  Genie.Assets.channels_support() # this should be done by `GenieAutoReload` instead of having to do it explicitly
  GenieAutoReload.assets()
%>
```
3/ in the controller pass `Genie` and `GenieAutoReload` to the layout via `context`:

```julia
using Genie, GenieAutoReload
function index()
  html(:foos, :index, context = @__MODULE__)
end
```
or via individual vars 

```julia
using Genie, GenieAutoReload
function index()
  html(:foos, :index, Genie = Genie, GenieAutoReload = GenieAutoReload)
end
```

**Comment by dmolina** [comment]
Thanks a lot for the quick answer.  I could not test it because the website has been adapted to Genie 3.0 and the plugin is not yet updated, but I am sure it will work nicely :-).
